import type { DocumentWithLinks } from './documentsTab.types'

export const FAKE_DOCUMENTS: DocumentWithLinks[] = [
  {
    id: 1,
    title: 'Sprint Plan',
    description: 'Initial sprint roadmap and task breakdown',
    fileType: 'application/pdf',
    uploaderName: 'Rahul',
    isArchived: false,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    links: [
      { id: 1, entityType: 'TASK', entityId: 10, entityTitle: 'Setup CI Pipeline' },
      { id: 2, entityType: 'MILESTONE', entityId: 1, entityTitle: 'Sprint 1' },
    ],
  },
  {
    id: 2,
    title: 'Database Schema',
    description: 'ERD and table relations for the backend',
    fileType: 'image/png',
    uploaderName: 'Utpal',
    isArchived: false,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    links: [
      { id: 3, entityType: 'DISCUSSION', entityId: 5, entityTitle: 'Backend Planning' },
    ],
  },
  {
    id: 3,
    title: 'API Documentation',
    description: 'REST endpoints and request/response schemas',
    fileType: 'application/json',
    uploaderName: 'Aman',
    isArchived: false,
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    links: [
      { id: 4, entityType: 'TASK', entityId: 12, entityTitle: 'Write API Docs' },
      { id: 5, entityType: 'TASK', entityId: 13, entityTitle: 'Review Endpoints' },
      { id: 6, entityType: 'DISCUSSION', entityId: 6, entityTitle: 'API Design Review' },
    ],
  },
  {
    id: 4,
    title: 'Design System',
    description: 'Colors, typography, and component guidelines',
    fileType: 'image/png',
    uploaderName: 'Neha',
    isArchived: false,
    createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    links: [],
  },
  {
    id: 5,
    title: 'Project Charter',
    description: 'Original project scope and objectives',
    fileType: 'application/pdf',
    uploaderName: 'Utpal',
    isArchived: false,
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    links: [],
  },
  {
    id: 6,
    title: 'Old Requirements',
    description: 'V1 requirements — superseded',
    fileType: 'application/pdf',
    uploaderName: 'Rahul',
    isArchived: true,
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    links: [],
  },
  {
    id: 7,
    title: 'Budget Sheet',
    description: 'Q1 resource allocation',
    fileType: 'application/vnd.ms-excel',
    uploaderName: 'Utpal',
    isArchived: true,
    createdAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
    links: [{ id: 7, entityType: 'MILESTONE', entityId: 2, entityTitle: 'Q1 Review' }],
  },
]
