const requiredEnv = (key: string): string => {
  const value = process.env[key]
  if (!value) throw new Error(`❌ Missing environment variable: ${key}`)
  return value
}

export const env = {
  CORS_ORIGIN: requiredEnv('CORS_ORIGIN'),
  PORT: requiredEnv('PORT'),
  STORAGE_PROVIDER: requiredEnv('STORAGE_PROVIDER'),
  GOOGLE_CLIENT_ID: requiredEnv('GOOGLE_LOGIN_CLIENT_ID'),
  GOOGLE_CLIENT_SECRET: requiredEnv('GOOGLE_LOGIN_CLIENT_SECRET'),
  GOOGLE_CALLBACK_URL: requiredEnv('GOOGLE_LOGIN_CALLBACK_URL'),
  GITHUB_CALLBACK_URL: requiredEnv('GITHUB_LOGIN_CALLBACK_URL'),
  GITHUB_CLIENT_ID: requiredEnv('GITHUB_LOGIN_CLIENT_ID'),
  GITHUB_CLIENT_SECRET: requiredEnv('GITHUB_LOGIN_CLIENT_SECRET'),
  ACCESS_TOKEN_SECRET: requiredEnv('ACCESS_TOKEN_SECRET'),
  REFRESH_TOKEN_SECRET: requiredEnv('REFRESH_TOKEN_SECRET'),
  ACCESS_TOKEN_EXPIRY: requiredEnv('ACCESS_TOKEN_EXPIRY'),
  REFRESH_TOKEN_EXPIRY: requiredEnv('REFRESH_TOKEN_EXPIRY'),
  CLIENT_URL: requiredEnv('CLIENT_URL'),
  EMAIL_HOST: requiredEnv('EMAIL_HOST'),
  EMAIL_PORT: requiredEnv('EMAIL_PORT'),
  BREVO_SMTP_USER: requiredEnv('BREVO_SMTP_USER'),
  BREVO_SMTP_PASS: requiredEnv('BREVO_SMTP_PASS'),
  R2_ACCESS_KEY_ID: requiredEnv('R2_ACCESS_KEY_ID'),
  R2_SECRET_ACCESS_KEY: requiredEnv('R2_SECRET_ACCESS_KEY'),
  R2_ENDPOINT: requiredEnv('R2_ENDPOINT'),
  R2_BUCKET_NAME: requiredEnv('R2_BUCKET_NAME'),
  R2_AVATAR_BUCKET_NAME: requiredEnv('R2_AVATAR_BUCKET_NAME'),
  R2_TOKEN_VALUE: requiredEnv('R2_TOKEN_VALUE'),
  R2_AVATARS_PUBLIC_BASE_URL: requiredEnv('R2_AVATARS_PUBLIC_BASE_URL'),
  GOOGLE_INTEGRATION_CALLBACK_URL: requiredEnv('GOOGLE_INTEGRATION_CALLBACK_URL'),
}
